/* ------------------------------------------------------------------------------------------------
FUNCTION:          name-of-function()
DESCRIPTION:       A brief description of this function ...
RETURNS:           What the function returns ... or not a value-returning function
NOTES:             Put other information here ...
------------------------------------------------------------------------------------------------ */
